//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class Car
    {
        public int ID { get; set; }
        public int Owner { get; set; }
        public int Model { get; set; }
        public int HorsePower { get; set; }
        public System.DateTime Year { get; set; }
        public string Color { get; set; }
    
        public virtual Model Models { get; set; }
        public virtual User User { get; set; }
    }
}
